backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'speakers'
    label: 'Speakers'
    description: 'Speakers on the DappCon conference'
    folder: 'src/pages/speakers'
    create: true
    slug: '{{name}}-{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'speaker' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: Image, name: image, widget: image }

  - name: 'events'
    label: 'Program Events'
    folder: 'src/pages/events'
    create: true
    slug: '{{title}}-{{speaker}}-{{startDate}}-{{endDate}}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'event' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Starts at', name: 'startDate', widget: 'datetime', format: 'DD.MM hh:mm' }
      - { label: 'Ends at', name: 'endDate', widget: 'datetime', format: 'DD.MM hh:mm' }
      - { label: 'Speaker', name: 'speaker', collection: 'speakers', searchFields: ['name'], valueField: 'name' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/privacy-policy/index.md'
        label: 'Privacy Policy'
        name: 'privacyPolicy'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'privacy-policy-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/index-page.md'
        label: 'Landing Page'
        name: 'landingPage'
        fields:
            - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - {label: 'Main Title', name: mainTitle, widget: string}
          - {label: 'Button Text', name: 'buttonText', widget: 'string'}
          - {label: 'About Dappcon', name: 'aboutDappcon', widget: 'text'}
          - {label: 'Stats', name: 'stats', widget: 'object', fields: [
              {label: 'First Stat', name: 'firstStat', widget: 'object', fields: [
                {label: 'Number', name: 'number', widget: 'string'},
                {label: 'Description', name: 'description', widget: 'string'}
              ]},
              {label: 'Second Stat', name: 'secondStat', widget: 'object', fields: [
                {label: 'Number', name: 'number', widget: 'string'},
                {label: 'Description', name: 'description', widget: 'string'}
              ]},
              {label: 'Third Stat', name: 'thirdState', widget: 'object', fields: [
                {label: 'Number', name: 'number', widget: 'string'},
                {label: 'Description', name: 'description', widget: 'string'}
              ]}
          ]}
          - {label: 'Program Photo Text', name: 'programPhotoText', widget: object, fields: [
              { label: "Label", name: "label", widget: "string" },
              { label: 'Should we make it a link?', name: 'isLink', widget: 'select', default: "No", options: ["Yes", "No"]},
              { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about)" }
            ]
          }
          - {label: 'About Gnosis', name: 'aboutGnosis', widget: 'text'}