backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  -
    name: speakers2019
    label: Speakers 2019
    description: 'Speakers of the DappCon 2019'
    folder: src/pages/speakers2019
    create: true
    slug: '{{name}}-{{slug}}'
    identifier_field: name
    fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: speaker2019
      -
        label: Name
        name: name
        widget: string
      -
        label: Company
        name: company
        widget: markdown
        hint: 'Format used here will be displayed on the website. Please dont use long lines'
      -
        label: Position
        name: position
        widget: markdown
        hint: 'Format used here will be displayed on the website. Please dont use long lines'
      -
        label: Image
        name: image
        widget: image
  -
    name: dapps
    label: Dapps
    description: 'Dapps of the DappCon 2020'
    folder: src/pages/dapps
    create: true
    slug: '{{name}}-{{slug}}'
    identifier_field: name
    fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: dapps2020
      -
        label: Name
        name: name
        widget: string
      -
        label: URL
        name: url
        widget: string
      -
        label: Logo
        name: logo
        widget: image
  -
    name: sponsors
    label: Sponsors
    description: 'Sponsors of the DappCon conference'
    folder: src/pages/sponsors
    create: true
    slug: '{{name}}-{{slug}}'
    identifier_field: name
    fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: sponsor
      -
        label: 'Sponsor Name'
        name: name
        widget: string
      -
        label: Image
        name: image
        widget: image
      -
        label: 'Website URL'
        name: url
        widget: string
      -
        label: 'Sponsorship package type'
        name: type
        widget: select
        options:
          -
            label: 'Gold (Unicorn)'
            value: 4
          -
            label: 'Silver (Whale)'
            value: 3
          -
            label: 'Bronze (Kitty)'
            value: 2
          -
            label: 'Iron (Knut)'
            value: 1
  -
    name: pages
    label: Pages
    files:
      -
        file: src/pages/tickets.md
        label: 'Tickets Page'
        name: tickets
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: tickets-page
          -
            label: 'Main Heading'
            name: heading
            widget: markdown
          -
            label: Columns
            name: columns
            widget: object
            fields:
              -
                label: 'Column 1'
                name: firstCol
                widget: object
                fields:
                  -
                    label: Title
                    name: title
                    widget: string
                  -
                    label: Description
                    name: description
                    widget: markdown
                  -
                    label: URL
                    name: url
                    widget: string
                  - 
                    label: Call to action
                    name: cta
                    widget: string
                  - 
                    label: Is Active?
                    name: isActive
                    hint: can the button be clicked?
                    widget: boolean
              -
                label: 'Column 2'
                name: secondCol
                widget: object
                fields:
                  -
                    label: Title
                    name: title
                    widget: string
                  -
                    label: Description
                    name: description
                    widget: markdown
                  -
                    label: URL
                    name: url
                    widget: string
                  - 
                    label: Call to action
                    name: cta
                    widget: string
                  - 
                    label: Is Active?
                    name: isActive
                    hint: can the button be clicked?
                    widget: boolean
              -
                label: 'Column 3'
                name: thirdCol
                widget: object
                fields:
                  -
                    label: Title
                    name: title
                    widget: string
                  -
                    label: Description
                    name: description
                    widget: markdown
                  -
                    label: URL
                    name: url
                    widget: string
                  - 
                    label: Call to action
                    name: cta
                    widget: string
                  - 
                    label: Is Active?
                    name: isActive
                    hint: can the button be clicked?
                    widget: boolean
      -
        file: src/pages/privacy-policy.md
        label: 'Privacy Policy'
        name: privacyPolicy
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: privacy-policy-page
          -
            label: Title
            name: title
            widget: string
          -
            label: Body
            name: body
            widget: markdown
      -
        file: src/pages/cookie-policy.md
        label: 'Cookie Policy'
        name: cookiePolicy
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: cookie-policy-page
          -
            label: Title
            name: title
            widget: string
          -
            label: Body
            name: body
            widget: markdown
      -
        file: src/pages/imprint.md
        label: Imprint
        name: imprint
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: imprint-page
          -
            label: Title
            name: title
            widget: string
          -
            label: Body
            name: body
            widget: markdown
      -
        file: src/pages/index-page.md
        label: 'Landing Page'
        name: landingPage
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: index-page
          -
            label: 'Main Title'
            name: mainTitle
            widget: string
          -
            label: 'Button Text'
            name: buttonText
            widget: string
          -
            label: 'Location and Date'
            name: locationAndDate
            widget: markdown
          -
            label: 'Buy Tickets Link'
            name: buyTicketsLink
            widget: string
          -
            label: 'Participate / Stats Heading'
            name: statsHeading
            widget: markdown
          -
            label: 'Participate / Stats sentence 1'
            name: statsSentence1
            widget: markdown
          -
            label: 'Participate / Stats sentence 2'
            name: statsSentence2
            widget: markdown
          -
            label: 'Dapps Section Text / Left Column'
            name: dappsTextLC
            widget: markdown
          -
            label: 'Dapps Section Text / Right Column'
            name: dappsTextRC
            widget: markdown
          -
            label: Stats
            name: stats
            widget: object
            fields:
              -
                label: 'First Stat'
                name: firstStat
                widget: object
                fields:
                  -
                    label: Number
                    name: number
                    widget: string
                  -
                    label: Description
                    name: description
                    widget: string
              -
                label: 'Second Stat'
                name: secondStat
                widget: object
                fields:
                  -
                    label: Number
                    name: number
                    widget: string
                  -
                    label: Description
                    name: description
                    widget: string
              -
                label: 'Third Stat'
                name: thirdStat
                widget: object
                fields:
                  -
                    label: Number
                    name: number
                    widget: string
                  -
                    label: Description
                    name: description
                    widget: string
          -
            label: Speakers 2019
            name: speakers2019
            widget: object
            fields:
              -
                label: 'Speaker 1'
                name: speaker1
                widget: relation
                collection: speakers2019
                searchFields:
                  - name
                valueField: name
              -
                label: 'Speaker 2'
                name: speaker2
                widget: relation
                collection: speakers2019
                searchFields:
                  - name
                valueField: name
              -
                label: 'Speaker 3'
                name: speaker3
                widget: relation
                collection: speakers2019
                searchFields:
                  - name
                valueField: name
              -
                label: 'Speaker 4'
                name: speaker4
                widget: relation
                collection: speakers2019
                searchFields:
                  - name
                valueField: name
              -
                label: 'Speaker 5'
                name: speaker5
                widget: relation
                collection: speakers2019
                searchFields:
                  - name
                valueField: name
              -
                label: 'Speaker 6'
                name: speaker6
                widget: relation
                collection: speakers2019
                searchFields:
                  - name
                valueField: name
          -
            label: 'Speaker Apply Link'
            name: speakerApplyLink
            widget: string
          -
            label: 'Sponsor Info Link'
            name: sponsorInfoLink
            widget: string
